/* Contenidos pedagógicos originales. La progresión temática se inspira en el manual de clase. */
const lesson=(level,label,title,intro,introFr,vocab,grammar,exercises,mission,missionFr,checks,production,productionFr)=>({level,label,title,intro,introFr,vocab,grammar,exercises,mission,missionFr,checks,production,productionFr});
const ex=(instruction,instructionFr,prompt,options,answer,tip,tipFr)=>({instruction,instructionFr,prompt,options,answer,tip,tipFr});
window.ENRICHED_LESSONS={
  bienvenido:lesson('seconde','UNIDAD 1 · A2','¡Bienvenido a mi vida!','Aprende a presentarte, habla de tu vida cotidiana y da la bienvenida a un compañero hispanohablante.','Apprends à te présenter, parle de ton quotidien et accueille un camarade hispanophone.',[
    ['Me llamo…','Je m’appelle…'],['Tengo quince años.','J’ai quinze ans.'],['Soy francés / francesa.','Je suis français / française.'],['Vivo en…','J’habite à…'],['Me levanto a las siete.','Je me lève à sept heures.'],['Empiezo las clases.','Je commence les cours.'],['Mi asignatura favorita','Ma matière préférée'],['Doy la bienvenida.','Je souhaite la bienvenue.']],
    [['SER','Identidad, origen y profesión','Identité, origine et profession','Soy alumno.'],['TENER','Edad y posesión','Âge et possession','Tengo quince años.'],['PRESENTE','Hábitos y rutina','Habitudes et routine','Estudio y vivo en Francia.']],
    [ex('Completa con el verbo correcto.','Complète avec le bon verbe.','Él ___ dieciséis años.',['tengo','tiene','tienes'],1,'Tener concuerda con él.','Tener s’accorde avec il.'),ex('Elige la presentación correcta.','Choisis la bonne présentation.','Hola, ___ Clara y ___ de Lyon.',['soy / me llamo','me llamo / soy','tengo / vivo'],1,'Primero damos el nombre y después el origen.','On donne d’abord le prénom puis l’origine.'),ex('Escoge la hora correcta.','Choisis l’heure correcte.','Las clases empiezan a las 8:30.',['a las ocho y media','a las ocho menos media','a la ocho y treinta'],0,'Media significa treinta minutos.','Media signifie trente minutes.'),ex('Completa la rutina.','Complète la routine.','Todos los días yo ___ a las siete.',['se levanta','me levanto','te levantas'],1,'Con yo usamos el pronombre me.','Avec yo, on utilise le pronom me.')],
    'Graba una presentación de 45 a 60 segundos.','Enregistre une présentation de 45 à 60 secondes.',['5 informaciones personales','3 asignaturas de tu horario','Una frase de bienvenida'],'Escribe primero seis frases sobre ti y ordénalas con después, luego y por fin.','Écris d’abord six phrases sur toi et organise-les avec después, luego et por fin.'),
  deporte:lesson('seconde','UNIDAD 2 · A2','Deporte, ¡te amo!','Habla de tus actividades, comprende una rutina deportiva y organiza un encuentro.','Parle de tes activités, comprends une routine sportive et organise une rencontre.',[
    ['entrenarse','s’entraîner'],['jugar al fútbol','jouer au football'],['hacer natación','faire de la natation'],['ganar / perder','gagner / perdre'],['el equipo','l’équipe'],['el torneo','le tournoi'],['estar en forma','être en forme'],['dos veces por semana','deux fois par semaine']],
    [['DIPTONGUE','e→ie / o→ue','Diphtongue','Quiero / puedo jugar.'],['PRONOMINALES','Rutinas personales','Habitudes personnelles','Me entreno cada día.'],['GUSTAR','Expresar gustos','Exprimer ses goûts','Me gusta correr.']],
    [ex('Completa con el verbo poder.','Complète avec le verbe poder.','Hoy nosotros no ___ entrenarnos.',['podemos','puedemos','pueden'],0,'Nosotros no hace diptongo.','Nosotros ne fait pas de diphtongue.'),ex('Elige el pronombre correcto.','Choisis le bon pronom.','Lucía ___ entrena por la tarde.',['me','te','se'],2,'Lucía corresponde a ella.','Lucía correspond à elle.'),ex('Expresa una preferencia.','Exprime une préférence.','A mí ___ el baloncesto.',['me gustan','me gusta','gusto'],1,'Baloncesto es singular.','Baloncesto est singulier.'),ex('Completa la frecuencia.','Complète la fréquence.','Entreno los martes y jueves: ___.',['cada día','dos veces por semana','nunca'],1,'Cuenta el número de días.','Compte le nombre de jours.')],
    'Crea y presenta el programa de un torneo en tu centro.','Crée et présente le programme d’un tournoi dans ton établissement.',['Deporte, lugar y horario','Reglas de participación','Una invitación motivadora'],'Compara tu rutina deportiva con la de un deportista imaginario.','Compare ta routine sportive à celle d’un sportif imaginaire.'),
  malaga:lesson('seconde','UNIDAD 3 · A2','¡Vamos a Málaga!','Aprende a orientarte, recomendar lugares y preparar una visita urbana.','Apprends à t’orienter, recommander des lieux et préparer une visite en ville.',[
    ['girar a la derecha','tourner à droite'],['seguir todo recto','continuer tout droit'],['cruzar la plaza','traverser la place'],['estar cerca / lejos','être près / loin'],['el casco antiguo','le centre historique'],['el paseo marítimo','la promenade maritime'],['visitar un museo','visiter un musée'],['merecer la pena','valoir la peine']],
    [['HAY / ESTÁ','Existencia y localización','Existence et localisation','Hay un museo. Está en el centro.'],['TENER QUE','Obligación personal','Obligation personnelle','Tienes que girar.'],['HAY QUE','Consejo general','Conseil général','Hay que reservar.']],
    [ex('Elige la forma correcta.','Choisis la bonne forme.','En Málaga ___ muchos museos.',['está','hay','es'],1,'Hay presenta lo que existe.','Hay présente ce qui existe.'),ex('Localiza el monumento.','Localise le monument.','La catedral ___ en el centro.',['hay','está','tiene'],1,'Estar localiza un elemento conocido.','Estar localise un élément connu.'),ex('Da una indicación.','Donne une indication.','Para llegar, tienes que ___ a la izquierda.',['giras','girar','girando'],1,'Después de tener que usamos infinitivo.','Après tener que, on emploie l’infinitif.'),ex('Formula un consejo general.','Formule un conseil général.','___ llevar agua en verano.',['Hay que','Tienes','Está'],0,'Hay que no menciona una persona concreta.','Hay que ne désigne personne en particulier.')],
    'Crea una audioguía con un recorrido de tres etapas.','Crée un audioguide avec un parcours en trois étapes.',['Tres lugares bien situados','Indicaciones para desplazarse','Una recomendación cultural'],'Escribe un comentario de 60 palabras para recomendar Málaga.','Écris un avis de 60 mots pour recommander Málaga.'),
  comida:lesson('seconde','UNIDAD 4 · A2','¡Comida para picar!','Descubre sabores, explica una receta y organiza un bufé hispánico.','Découvre des saveurs, explique une recette et organise un buffet hispanique.',[
    ['los ingredientes','les ingrédients'],['cortar en trozos','couper en morceaux'],['añadir / mezclar','ajouter / mélanger'],['cocer / freír','cuire / frire'],['dulce / salado','sucré / salé'],['una ración','une portion'],['tener hambre','avoir faim'],['¡Que aproveche!','Bon appétit !']],
    [['GUSTAR','Gusto singular o plural','Goût singulier ou pluriel','Me gusta el arroz. Me gustan las tapas.'],['SE + VERBO','Generalidad','Généralité','Se corta la cebolla.'],['IMPERATIVO TÚ','Dar instrucciones','Donner des instructions','Corta y mezcla.']],
    [ex('Expresa un gusto.','Exprime un goût.','Me ___ las aceitunas.',['gusta','gustan','gusto'],1,'El sujeto aceitunas es plural.','Le sujet aceitunas est pluriel.'),ex('Completa una receta impersonal.','Complète une recette impersonnelle.','Primero, ___ cortan los tomates.',['se','te','me'],0,'Se permite explicar sin nombrar al cocinero.','Se permet d’expliquer sans nommer le cuisinier.'),ex('Ordena una instrucción.','Ordonne une instruction.','Después, ___ el aceite.',['añades','añade','añadir'],1,'El imperativo de tú termina aquí en -e.','L’impératif de tú se termine ici par -e.'),ex('Elige el utensilio lógico.','Choisis l’ustensile logique.','Para cortar necesito ___.',['una sartén','un cuchillo','un vaso'],1,'Cortar se hace con un cuchillo.','On coupe avec un couteau.')],
    'Presenta una tapa y defiende su presencia en el bufé.','Présente une tapa et justifie sa place dans le buffet.',['Ingredientes y cantidades','Cuatro pasos de preparación','Origen y elección personal'],'Redacta una receta clara usando cuatro conectores cronológicos.','Rédige une recette claire avec quatre connecteurs chronologiques.'),
  moda:lesson('seconde','UNIDAD 5 · A2+','¡La moda mola!','Describe personas y prendas, compara estilos y habla de ropa profesional.','Décris des personnes et des vêtements, compare des styles et parle de tenue professionnelle.',[
    ['llevar puesto','porter'],['quedar bien','aller bien'],['probarse','essayer'],['una camisa de rayas','une chemise rayée'],['unos zapatos cómodos','des chaussures confortables'],['elegante / informal','élégant / décontracté'],['más barato que','moins cher que'],['la ropa de trabajo','la tenue de travail']],
    [['SER / ESTAR','Característica o estado','Caractéristique ou état','Es elegante. Está cansado.'],['COMPARATIVO','Más / menos / tan','Comparatif','Es más cómodo que.'],['CONCORDANCIA','Género y número','Genre et nombre','Camisas blancas.']],
    [ex('Describe una característica.','Décris une caractéristique.','La chaqueta ___ elegante.',['es','está','hay'],0,'La elegancia se presenta como característica.','L’élégance est présentée comme une caractéristique.'),ex('Compara dos prendas.','Compare deux vêtements.','Estas botas son ___ cómodas que aquellas.',['más','tan','muy'],0,'Más… que expresa superioridad.','Más… que exprime la supériorité.'),ex('Haz la concordancia.','Fais l’accord.','Lleva una camisa ___.',['blancos','blanca','blanco'],1,'Camisa es femenino singular.','Camisa est féminin singulier.'),ex('Expresa igualdad.','Exprime l’égalité.','El uniforme es ___ práctico como el chándal.',['más','tanto','tan'],2,'Tan + adjetivo + como.','Tan + adjectif + como.')],
    'Presenta y compara una ropa cotidiana y una ropa profesional.','Présente et compare une tenue quotidienne et une tenue professionnelle.',['Descripción precisa','Dos comparaciones','Justificación profesional'],'Prepara el guion de un vídeo de moda responsable.','Prépare le script d’une vidéo sur la mode responsable.'),
  series:lesson('seconde','UNIDAD 6 · A2+','Estrenos de nueva temporada','Cuenta qué está pasando, presenta una serie y escribe una crítica sencilla.','Raconte ce qui se passe, présente une série et écris une critique simple.',[
    ['el argumento','l’intrigue'],['un capítulo','un épisode'],['el reparto','la distribution'],['el personaje principal','le personnage principal'],['estar enganchado/a','être accro'],['emocionante','passionnant'],['aburrido/a','ennuyeux'],['recomendar','recommander']],
    [['ESTAR + GERUNDIO','Acción en curso','Action en cours','Está investigando.'],['OPINIÓN','Creo que / me parece que','Opinion','Me parece que es original.'],['RECOMENDAR QUE','Subjuntivo inicial','Première approche du subjonctif','Recomiendo que veas la serie.']],
    [ex('Describe una acción.','Décris une action.','Los personajes están ___.',['correr','corriendo','corren'],1,'Estar se combina con el gerundio.','Estar se combine avec le gérondif.'),ex('Expresa tu opinión.','Exprime ton opinion.','___ la serie es divertida.',['Creo que','Tengo que','Hay que'],0,'Creo que introduce una opinión.','Creo que introduit une opinion.'),ex('Formula una recomendación.','Formule une recommandation.','Te recomiendo que ___ el primer capítulo.',['ves','veas','ver'],1,'Recomendar que activa el subjuntivo.','Recomendar que entraîne le subjonctif.'),ex('Elige el elemento correcto.','Choisis le bon élément.','La persona que interpreta un papel forma parte del ___.',['argumento','reparto','capítulo'],1,'El reparto reúne a actores y actrices.','Le reparto réunit les acteurs et actrices.')],
    'Graba una recomendación de un minuto sobre una serie imaginaria.','Enregistre une recommandation d’une minute sur une série imaginaire.',['Título y argumento','Personajes principales','Opinión justificada'],'Escribe una crítica breve con una cualidad y un defecto.','Écris une courte critique avec une qualité et un défaut.'),
  'pura-vida':lesson('premiere','UNIDAD 1 · A2+','¡Pura vida!','Organiza un viaje responsable, pide información y convence a un compañero.','Organise un voyage responsable, demande des informations et convaincs un camarade.',[
    ['el alojamiento','l’hébergement'],['reservar una habitación','réserver une chambre'],['hacer senderismo','faire de la randonnée'],['la selva tropical','la forêt tropicale'],['respetar la fauna','respecter la faune'],['el presupuesto','le budget'],['ida y vuelta','aller-retour'],['disfrutar del viaje','profiter du voyage']],
    [['IMPERATIVO','Promocionar y aconsejar','Promouvoir et conseiller','Descubre Costa Rica.'],['FUTURO','Presentar un programa','Présenter un programme','Visitaremos un parque.'],['INTERROGATIVOS','Pedir información','Demander des informations','¿Cuánto cuesta?']],
    [ex('Promociona una actividad.','Fais la promotion d’une activité.','___ la naturaleza de Costa Rica.',['Descubres','Descubre','Descubrir'],1,'Usamos el imperativo para invitar.','On utilise l’impératif pour inviter.'),ex('Anuncia el programa.','Annonce le programme.','Mañana nosotros ___ la reserva.',['confirmamos','confirmaremos','confirmaríamos'],1,'Mañana orienta hacia el futuro.','Mañana indique le futur.'),ex('Pide un precio.','Demande un prix.','¿___ cuesta una noche?',['Dónde','Cuánto','Cuándo'],1,'Cuánto pregunta por una cantidad.','Cuánto demande une quantité.'),ex('Elige una práctica responsable.','Choisis une pratique responsable.','En un parque natural debemos ___.',['dejar residuos','respetar los senderos','molestar a los animales'],1,'El turismo sostenible protege el entorno.','Le tourisme durable protège l’environnement.')],
    'Presenta un viaje sostenible y convence a un amigo.','Présente un voyage durable et convaincs un ami.',['Programa de tres días','Presupuesto aproximado','Tres compromisos responsables'],'Redacta un correo para pedir información a un alojamiento.','Rédige un courriel pour demander des informations à un hébergement.'),
  fiesta:lesson('premiere','UNIDAD 2 · A2+','¡Vámonos de fiesta!','Compara celebraciones, comprende su significado y presenta un evento.','Compare des fêtes, comprends leur signification et présente un événement.',[
    ['celebrar','fêter'],['disfrazarse','se déguiser'],['el desfile','le défilé'],['los fuegos artificiales','les feux d’artifice'],['tener lugar','avoir lieu'],['atraer a visitantes','attirer des visiteurs'],['una tradición','une tradition'],['inolvidable','inoubliable']],
    [['SUPERLATIVO','El/la más…','Superlatif','Es la fiesta más conocida.'],['-ÍSIMO','Intensidad','Intensité','Es divertidísima.'],['TAN… QUE','Consecuencia','Conséquence','Es tan popular que atrae a miles.']],
    [ex('Forma un superlativo.','Forme un superlatif.','Es ___ celebración más antigua.',['la','la más','más la'],1,'El superlativo incluye artículo + más.','Le superlatif comprend article + más.'),ex('Intensifica el adjetivo.','Renforce l’adjectif.','La fiesta es muy divertida: es ___.',['divertidaísima','divertidísima','más divertida'],1,'Quitamos la vocal final antes de -ísima.','On retire la voyelle finale avant -ísima.'),ex('Expresa una consecuencia.','Exprime une conséquence.','Hay ___ gente que las calles están llenas.',['tan','tanta','tanto'],1,'Gente es femenino singular.','Gente est féminin singulier.'),ex('Elige la información esencial.','Choisis l’information essentielle.','Para presentar una fiesta indicamos ___.',['fecha, lugar y significado','solo el color','únicamente el precio'],0,'Una presentación debe situar y explicar.','Une présentation doit situer et expliquer.')],
    'Diseña y presenta un evento cultural para el instituto.','Conçois et présente un événement culturel pour le lycée.',['Fecha, lugar y público','Programa de actividades','Explicación cultural'],'Compara dos celebraciones sin decidir que una cultura es superior.','Compare deux fêtes sans hiérarchiser les cultures.'),
  tecnologias:lesson('premiere','UNIDAD 3 · B1','Tecnologías para mejorar el mundo','Analiza usos digitales y aconseja una tecnología útil e inclusiva.','Analyse les usages numériques et conseille une technologie utile et inclusive.',[
    ['un dispositivo conectado','un appareil connecté'],['la brecha digital','la fracture numérique'],['proteger los datos','protéger les données'],['la contraseña','le mot de passe'],['accesible','accessible'],['facilitar la vida','faciliter la vie'],['descargar una aplicación','télécharger une application'],['hacer un uso responsable','utiliser de façon responsable']],
    [['ACONSEJAR QUE','Consejo + subjuntivo','Conseil + subjonctif','Te aconsejo que limites el tiempo.'],['PROHIBIR QUE','Prohibición + subjuntivo','Interdiction + subjonctif','Prohíben que uses el móvil.'],['IMPERFECTO','Hábitos pasados','Habitudes passées','Antes llamábamos por teléfono.']],
    [ex('Da un consejo.','Donne un conseil.','Te aconsejo que ___ tus datos.',['proteges','protejas','proteger'],1,'Tras aconsejar que usamos subjuntivo.','Après aconsejar que, on emploie le subjonctif.'),ex('Habla de antes.','Parle d’autrefois.','Antes mis abuelos no ___ internet.',['usaban','usaron','usarán'],0,'El imperfecto describe hábitos.','L’imparfait décrit des habitudes.'),ex('Formula una prohibición.','Formule une interdiction.','La escuela prohíbe que se ___ durante el examen.',['conecta','conecte','conectará'],1,'Prohibir que pide subjuntivo.','Prohibir que demande le subjonctif.'),ex('Elige una contraseña segura.','Choisis un mot de passe sûr.','¿Qué contraseña es más segura?',['123456','mi_nombre','Río!27Nube#'],2,'Combina caracteres sin información evidente.','Combine des caractères sans information évidente.')],
    'Asesora a una persona que busca un dispositivo conectado.','Conseille une personne qui cherche un appareil connecté.',['Necesidades del usuario','Dos ventajas y un límite','Consejos de seguridad'],'Graba un mensaje con tres normas para un uso digital responsable.','Enregistre un message avec trois règles d’usage numérique responsable.'),
  mujeres:lesson('premiere','UNIDAD 4 · B1','¡Arriba mujeres!','Narra una trayectoria, sitúa acontecimientos y explica un compromiso.','Raconte un parcours, situe des événements et explique un engagement.',[
    ['luchar por','lutter pour'],['defender los derechos','défendre les droits'],['lograr / conseguir','parvenir à'],['ser pionera','être pionnière'],['fundar una asociación','fonder une association'],['superar obstáculos','surmonter des obstacles'],['recibir un premio','recevoir un prix'],['dejar un legado','laisser un héritage']],
    [['INDEFINIDO','Acciones terminadas','Actions terminées','Fundó una escuela.'],['POR / PARA','Causa, medio o finalidad','Cause, moyen ou but','Luchó por sus derechos para cambiar la sociedad.'],['FECHAS','Situar acontecimientos','Situer des événements','En 1998 recibió un premio.']],
    [ex('Narra un hecho terminado.','Raconte un fait terminé.','En 2010 ella ___ una asociación.',['funda','fundó','fundaba'],1,'Una fecha cerrada pide indefinido.','Une date fermée demande le passé simple.'),ex('Expresa la finalidad.','Exprime le but.','Trabajó ___ mejorar la educación.',['por','para','porque'],1,'Para + infinitivo expresa finalidad.','Para + infinitif exprime le but.'),ex('Expresa una causa.','Exprime une cause.','Fue reconocida ___ su compromiso.',['para','por','hacia'],1,'Por introduce aquí la causa.','Por introduit ici la cause.'),ex('Ordena una biografía.','Ordonne une biographie.','¿Qué conector inicia normalmente el final?',['Al principio','Años después','Antes de nacer'],1,'Años después permite avanzar en el tiempo.','Años después permet d’avancer dans le temps.')],
    'Presta tu voz a una mujer comprometida y presenta su trayectoria.','Prête ta voix à une femme engagée et présente son parcours.',['Contexto y fechas','Obstáculos y logros','Legado actual'],'Crea una línea del tiempo con cinco hitos y fuentes verificables.','Crée une frise avec cinq étapes et des sources vérifiables.'),
  perfil:lesson('premiere','UNIDAD 5 · B1','¡El mejor perfil!','Identifica competencias, comprende una oferta y prepara una entrevista.','Identifie des compétences, comprends une offre et prépare un entretien.',[
    ['una oferta de prácticas','une offre de stage'],['presentar su candidatura','présenter sa candidature'],['tener experiencia','avoir de l’expérience'],['ser puntual','être ponctuel'],['trabajar en equipo','travailler en équipe'],['atender al cliente','accueillir le client'],['dominar un programa','maîtriser un logiciel'],['estar disponible','être disponible']],
    [['OBLIGACIÓN','Hay que / tener que','Obligation','Hay que ser puntual.'],['ES PRECISO QUE','Necesidad + subjuntivo','Nécessité + subjonctif','Es preciso que seas autónomo.'],['INDEFINIDOS IRREG.','Experiencias terminadas','Expériences terminées','Hice prácticas y tuve responsabilidades.']],
    [ex('Expresa una competencia necesaria.','Exprime une compétence nécessaire.','Es preciso que el candidato ___ puntual.',['es','sea','será'],1,'Es preciso que activa el subjuntivo.','Es preciso que entraîne le subjonctif.'),ex('Cuenta una experiencia.','Raconte une expérience.','El año pasado ___ prácticas en una tienda.',['hago','hice','hacía'],1,'Hacer se convierte en hice.','Hacer devient hice.'),ex('Elige la fórmula profesional.','Choisis la formule professionnelle.','Al comenzar una entrevista digo:',['¿Qué pasa?','Buenos días, encantado/a.','¡Hasta luego!'],1,'El registro debe adaptarse al contexto.','Le registre doit s’adapter au contexte.'),ex('Identifica un saber estar.','Identifie un savoir-être.','¿Cuál es una cualidad profesional?',['Manejar Excel','Hablar español','Ser organizado/a'],2,'La organización describe una actitud profesional.','L’organisation décrit une attitude professionnelle.')],
    'Graba un videocurrículum claro de 90 segundos.','Enregistre un CV vidéo clair de 90 secondes.',['Formación y especialidad','Experiencia o proyecto','Tres competencias justificadas'],'Simula cinco preguntas de entrevista con un compañero.','Simule cinq questions d’entretien avec un camarade.'),
  erasmus:lesson('terminale','UNIDAD 6 · B1','Un billete para Erasmus+','Imagina una movilidad profesional, presenta tus motivaciones y prepara tu candidatura.','Imagine une mobilité professionnelle, présente tes motivations et prépare ta candidature.',[
    ['solicitar unas prácticas','demander un stage'],['adquirir experiencia','acquérir de l’expérience'],['mejorar mi nivel','améliorer mon niveau'],['trabajar en equipo','travailler en équipe'],['adaptarse','s’adapter'],['alojarse','se loger'],['salir de su zona de confort','sortir de sa zone de confort'],['una beca de movilidad','une bourse de mobilité']],
    [['FUTURO','Presentar un proyecto','Présenter un projet','Trabajaré en España.'],['CONDICIONAL','Expresar un deseo','Exprimer un souhait','Me gustaría participar.'],['CARTA FORMAL','Organizar una solicitud','Organiser une demande','Me dirijo a usted para…']],
    [ex('Expresa un deseo.','Exprime un souhait.','Me gustaría ___ unas prácticas en Valencia.',['hacer','haré','hice'],0,'Después de gustaría usamos infinitivo.','Après gustaría, on emploie l’infinitif.'),ex('Presenta tu proyecto.','Présente ton projet.','Durante la movilidad ___ en una empresa local.',['trabajaría','trabajé','trabajaré'],2,'El proyecto previsto se expresa aquí en futuro.','Le projet prévu s’exprime ici au futur.'),ex('Elige una fórmula formal.','Choisis une formule formelle.','Para comenzar una candidatura:',['Hola, ¿qué tal?','Me dirijo a usted para presentar mi candidatura.','Oye, quiero ir.'],1,'Una candidatura exige un registro formal.','Une candidature exige un registre formel.'),ex('Relaciona objetivo y beneficio.','Relie objectif et bénéfice.','Mejorar el español me permitirá ___.',['comunicarme con clientes','olvidar mi formación','evitar toda autonomía'],0,'Una movilidad desarrolla competencias reales.','Une mobilité développe des compétences concrètes.')],
    'Graba un vídeo breve para presentar tu candidatura Erasmus+.','Enregistre une courte vidéo pour présenter ta candidature Erasmus+.',['Tu formación y especialidad','Dos motivaciones personales','Dos beneficios profesionales'],'Redacta una carta formal de 120 palabras y revísala con una lista de criterios.','Rédige une lettre formelle de 120 mots et relis-la avec une grille.'),
  planeta:lesson('terminale','UNIDAD 7 · B1','¡Luchemos por la vida!','Comprende problemas ambientales, expresa emociones y defiende soluciones.','Comprends des problèmes environnementaux, exprime des émotions et défends des solutions.',[
    ['el cambio climático','le changement climatique'],['los residuos','les déchets'],['ahorrar agua','économiser l’eau'],['las energías renovables','les énergies renouvelables'],['la biodiversidad','la biodiversité'],['reducir la huella','réduire l’empreinte'],['tomar medidas','prendre des mesures'],['concienciar','sensibiliser']],
    [['EMOCIÓN + QUE','Subjuntivo','Émotion + subjonctif','Me preocupa que desaparezcan especies.'],['CONDICIONAL','Proponer soluciones','Proposer des solutions','Podríamos reciclar más.'],['ARGUMENTAR','Causa y consecuencia','Cause et conséquence','Como…, por eso…']],
    [ex('Expresa una preocupación.','Exprime une inquiétude.','Me preocupa que el planeta ___ más calor.',['sufre','sufra','sufrirá'],1,'Una emoción seguida de que pide subjuntivo.','Une émotion suivie de que demande le subjonctif.'),ex('Propón una solución.','Propose une solution.','Nosotros ___ instalar paneles solares.',['podríamos','pudimos','podemos ayer'],0,'El condicional suaviza la propuesta.','Le conditionnel nuance la proposition.'),ex('Expresa una consecuencia.','Exprime une conséquence.','Consumimos demasiado; ___, producimos más residuos.',['sin embargo','por eso','aunque'],1,'Por eso introduce la consecuencia.','Por eso introduit la conséquence.'),ex('Elige una medida eficaz.','Choisis une mesure efficace.','Para reducir residuos, el instituto puede ___.',['usar botellas reutilizables','imprimir todo dos veces','tirar pilas a la basura'],0,'Reutilizar evita residuos.','Réutiliser évite des déchets.')],
    'Participa en un debate y redacta una propuesta ecológica para el centro.','Participe à un débat et rédige une proposition écologique pour l’établissement.',['Problema claramente explicado','Tres medidas realistas','Argumentos y concesión'],'Prepara una intervención: opinión, dos argumentos, ejemplo y conclusión.','Prépare une intervention : opinion, deux arguments, exemple et conclusion.'),
  colombia:lesson('terminale','UNIDAD 8 · B1','Colombia: ¡basta de prejuicios!','Cuestiona ideas preconcebidas y presenta una Colombia contemporánea y diversa.','Remets en question les idées reçues et présente une Colombie contemporaine et diverse.',[
    ['un prejuicio','un préjugé'],['una idea preconcebida','une idée reçue'],['la diversidad','la diversité'],['poner en valor','mettre en valeur'],['un referente','une personnalité de référence'],['la innovación','l’innovation'],['la memoria','la mémoire'],['cambiar la mirada','changer le regard']],
    [['PRETÉRITO PERFECTO','Pasado conectado al presente','Passé lié au présent','Colombia ha cambiado.'],['FINALIDAD','Para / para que','But','Informamos para que cambie la mirada.'],['CONTRASTE','No solo… sino también','Contraste','No solo exporta café, sino también creatividad.']],
    [ex('Conecta pasado y presente.','Relie passé et présent.','En los últimos años Colombia ___ mucho.',['cambió','ha cambiado','cambiará'],1,'En los últimos años mantiene vínculo con el presente.','En los últimos años garde un lien avec le présent.'),ex('Expresa una finalidad.','Exprime un but.','Creamos la campaña para que el público ___ otra realidad.',['descubre','descubra','descubrir'],1,'Para que se construye con subjuntivo.','Para que se construit avec le subjonctif.'),ex('Amplía una idea.','Élargis une idée.','Colombia no solo tiene paisajes, ___ una gran diversidad cultural.',['pero','sino también','porque'],1,'No solo se completa con sino también.','No solo se complète avec sino también.'),ex('Evalúa una fuente.','Évalue une source.','La fuente más fiable para un dato oficial es ___.',['un comentario anónimo','un organismo público identificado','un rumor sin fecha'],1,'Autoría, fecha y procedencia importan.','Auteur, date et provenance comptent.')],
    'Crea una presentación que desmonte tres prejuicios con datos y ejemplos.','Crée une présentation qui déconstruit trois préjugés avec des données et exemples.',['Tres ideas preconcebidas','Fuentes identificadas','Realidades culturales diversas'],'Escribe un texto que distinga hecho, opinión y estereotipo.','Écris un texte qui distingue fait, opinion et stéréotype.'),
  arte:lesson('terminale','UNIDAD 9 · B1','Mi arte, mi arma','Interpreta obras comprometidas y crea un mensaje respetuoso y argumentado.','Interprète des œuvres engagées et crée un message respectueux et argumenté.',[
    ['una obra comprometida','une œuvre engagée'],['denunciar','dénoncer'],['reivindicar','revendiquer'],['la libertad de expresión','la liberté d’expression'],['transmitir un mensaje','transmettre un message'],['conmover','émouvoir'],['una metáfora','une métaphore'],['dar voz a','donner une voix à']],
    [['GERUNDIO','Manera o simultaneidad','Manière ou simultanéité','Protesta cantando.'],['IMPERATIVO NEGATIVO','No + subjuntivo','Impératif négatif','No calles.'],['INTERPRETAR','Puede simbolizar…','Interpréter','Este color puede representar…']],
    [ex('Expresa la manera.','Exprime la manière.','La artista denuncia la injusticia ___ un mural.',['pintando','pintar','pinta'],0,'El gerundio explica cómo actúa.','Le gérondif explique comment elle agit.'),ex('Formula una prohibición.','Formule une interdiction.','___ la voz ante la injusticia.',['No calla','No calles','No callar'],1,'El imperativo negativo de tú usa subjuntivo.','L’impératif négatif de tú utilise le subjonctif.'),ex('Propón una interpretación prudente.','Propose une interprétation prudente.','Para interpretar una imagen digo:',['Significa obligatoriamente…','Puede simbolizar…','No tiene ningún sentido.'],1,'Interpretar no significa imponer una única lectura.','Interpréter ne consiste pas à imposer une seule lecture.'),ex('Identifica una función del arte.','Identifie une fonction de l’art.','Una obra comprometida puede ___.',['abrir un debate','eliminar toda opinión','prohibir la reflexión'],0,'El arte puede interpelar y provocar diálogo.','L’art peut interpeller et ouvrir le dialogue.')],
    'Crea y presenta una producción artística comprometida.','Crée et présente une production artistique engagée.',['Tema y público definidos','Recursos expresivos explicados','Mensaje argumentado y respetuoso'],'Analiza una imagen: descripción, interpretación y opinión personal.','Analyse une image : description, interprétation et avis personnel.'),
  bac:lesson('terminale','RECORRIDO · B1','Recorrido Bac','Entrénate con estrategias claras para comprender, hablar, interactuar y escribir.','Entraîne-toi avec des stratégies claires pour comprendre, parler, interagir et écrire.',[
    ['la naturaleza del documento','la nature du document'],['el tema principal','le thème principal'],['la intención','l’intention'],['los datos relevantes','les données pertinentes'],['dar su opinión','donner son avis'],['justificar','justifier'],['reformular','reformuler'],['concluir','conclure']],
    [['CONECTORES','Estructurar','Structurer','Primero, además, sin embargo, por fin.'],['CUENTA RENDIDA','Naturaleza, tema, información, objetivo','Compte rendu','Se trata de… El objetivo es…'],['INTERACCIÓN','Mantener el diálogo','Maintenir le dialogue','¿Puede repetir, por favor?']],
    [ex('Identifica el primer paso.','Identifie la première étape.','Al descubrir un documento, primero busco ___.',['cada palabra desconocida','su naturaleza y tema','una traducción completa'],1,'La comprensión global viene antes del detalle.','La compréhension globale précède le détail.'),ex('Estructura un argumento.','Structure un argument.','___, esta solución es útil; sin embargo, cuesta mucho.',['En mi opinión','Ayer','Debajo'],0,'En mi opinión anuncia un punto de vista.','En mi opinión annonce un point de vue.'),ex('Mantén la interacción.','Maintiens l’interaction.','Si no comprendes, dices:',['No sé nada.','¿Puede repetir, por favor?','Adiós.'],1,'Pedir repetición es una estrategia válida.','Demander de répéter est une stratégie valable.'),ex('Concluye con claridad.','Conclue clairement.','___, esta experiencia me permitió progresar.',['Para concluir','En el centro','Antes que'],0,'Para concluir anuncia el cierre.','Para concluir annonce la fin.')],
    'Realiza una simulación completa y autoevalúate con la rúbrica.','Réalise une simulation complète et autoévalue-toi avec la grille.',['Preparación cronometrada','Producción estructurada','Autoevaluación y mejora'],'Graba dos versiones de tu oral y explica qué mejoraste.','Enregistre deux versions de ton oral et explique tes progrès.')
};
