/* Textos originales para comprensión escrita y oral. No reproducen documentos del manual. */
window.UNIT_MEDIA={
  bienvenido:{title:'El primer día de Inés',text:'Inés tiene quince años y vive cerca de Zaragoza. Cada mañana se levanta a las siete, desayuna con su hermano y va al instituto en autobús. Sus clases empiezan a las ocho y media. Le gustan la informática y el español, pero no le gustan mucho las matemáticas. Por la tarde hace los deberes y juega al baloncesto.',gloss:[['cerca de','près de'],['cada mañana','chaque matin'],['los deberes','les devoirs']],q:'¿Cómo va Inés al instituto?',options:['A pie','En autobús','En tren'],answer:1,pron:'Me llamo Inés y mis clases empiezan a las ocho y media.'},
  deporte:{title:'Un club para todos',text:'El club deportivo del instituto abre los miércoles por la tarde. Los alumnos pueden practicar fútbol, voleibol o atletismo. No es necesario tener mucha experiencia: lo importante es participar, respetar al equipo y disfrutar. Sara se entrena dos veces por semana porque quiere estar en forma y conocer a otros jóvenes.',gloss:[['abre','ouvre'],['tener experiencia','avoir de l’expérience'],['disfrutar','profiter']],q:'¿Qué considera importante el club?',options:['Ganar siempre','Participar y respetar','Entrenar cada día'],answer:1,pron:'Me entreno dos veces por semana y respeto a mi equipo.'},
  malaga:{title:'Una mañana en el centro',text:'Leo empieza su visita en la plaza de la Constitución. Primero sigue todo recto hasta la catedral. Después gira a la derecha para visitar un museo. A mediodía camina hacia el puerto y come cerca del paseo marítimo. El recorrido es fácil, pero hay que llevar agua porque en verano hace mucho calor.',gloss:[['a mediodía','à midi'],['hacia','vers'],['llevar agua','emporter de l’eau']],q:'¿Dónde come Leo?',options:['Cerca del puerto','En la catedral','En la estación'],answer:0,pron:'Sigue todo recto y gira a la derecha después de la plaza.'},
  comida:{title:'Una merienda compartida',text:'Para la semana de las lenguas, cada grupo prepara una especialidad. Marta propone pan con tomate. Primero corta el pan y los tomates. Después añade aceite de oliva y un poco de sal. Es una receta sencilla y económica. Sus compañeros preparan otras tapas para crear una mesa variada y descubrir nuevos sabores.',gloss:[['una merienda','un goûter'],['aceite de oliva','huile d’olive'],['sabores','saveurs']],q:'¿Por qué preparan diferentes tapas?',options:['Para venderlas','Para descubrir sabores','Para una competición'],answer:1,pron:'Primero corta los tomates y después añade aceite de oliva.'},
  moda:{title:'Ropa cómoda y profesional',text:'Nora estudia comercio y realiza prácticas en una tienda. Para ir a clase lleva vaqueros, zapatillas y una sudadera. En la tienda elige un pantalón oscuro, una camisa blanca y zapatos cómodos. Su ropa profesional es más formal que su ropa cotidiana, pero las dos son prácticas y reflejan su personalidad.',gloss:[['realiza prácticas','fait un stage'],['vaqueros','jean'],['reflejan','reflètent']],q:'¿Cómo es la ropa de Nora en la tienda?',options:['Más formal','Más deportiva','Menos cómoda'],answer:0,pron:'Mi ropa profesional es más formal que mi ropa cotidiana.'},
  series:{title:'El misterio del barrio',text:'Una nueva serie cuenta la historia de cuatro amigos que investigan sucesos extraños en su barrio. En el primer capítulo están buscando un objeto desaparecido. La protagonista es curiosa y valiente, pero a veces actúa sin pensar. La serie mezcla humor y misterio. Diego la recomienda porque los personajes son creíbles y el argumento es original.',gloss:[['sucesos','événements'],['desaparecido','disparu'],['creíbles','crédibles']],q:'¿Por qué recomienda Diego la serie?',options:['Porque es muy corta','Por sus personajes y argumento','Porque conoce al reparto'],answer:1,pron:'Los cuatro amigos están investigando un misterio en su barrio.'},
  'pura-vida':{title:'Viajar sin dejar huella',text:'Clara viajará a Costa Rica durante diez días. Se alojará en un pequeño establecimiento que utiliza energía solar. Visitará un parque natural con una guía local y llevará una botella reutilizable. También respetará los senderos y observará a los animales desde lejos. Su objetivo es disfrutar de la naturaleza sin dañarla.',gloss:[['se alojará','elle logera'],['senderos','sentiers'],['sin dañarla','sans l’abîmer']],q:'¿Qué hará Clara para reducir residuos?',options:['Llevará una botella reutilizable','Comprará botellas cada día','No beberá agua'],answer:0,pron:'Respetaremos los senderos y observaremos a los animales desde lejos.'},
  fiesta:{title:'Una celebración abierta',text:'El instituto organiza una jornada dedicada a las celebraciones del mundo hispánico. Cada clase presenta una tradición después de investigar su origen y su significado actual. Habrá música, exposiciones y pequeños talleres. La jornada no pretende imitar las fiestas, sino comprenderlas y presentarlas con respeto, evitando disfraces o imágenes estereotipadas.',gloss:[['una jornada','une journée'],['talleres','ateliers'],['evitando','en évitant']],q:'¿Cuál es el objetivo de la jornada?',options:['Elegir la mejor fiesta','Comprender las tradiciones','Vender disfraces'],answer:1,pron:'Presentaremos las tradiciones con curiosidad y respeto.'},
  tecnologias:{title:'Una aplicación sencilla',text:'Una asociación ha creado una aplicación para personas que no se sienten cómodas con la tecnología. Los botones son grandes, las instrucciones son claras y el usuario puede pedir ayuda fácilmente. Antes, algunos miembros de la asociación dependían de otras personas para hacer una videollamada. Ahora pueden comunicarse con más autonomía.',gloss:[['ha creado','a créé'],['pedir ayuda','demander de l’aide'],['dependían','dépendaient']],q:'¿Qué ha cambiado gracias a la aplicación?',options:['Los usuarios tienen más autonomía','Los teléfonos son más caros','Hay menos comunicación'],answer:0,pron:'Te aconsejo que elijas una aplicación clara y accesible.'},
  mujeres:{title:'Una ingeniera que abre caminos',text:'Elena García estudió ingeniería y comenzó su carrera en un pequeño laboratorio. Años después dirigió un equipo dedicado a mejorar sistemas de transporte. También creó talleres para animar a las jóvenes a descubrir profesiones científicas. Recibió varios reconocimientos por su trabajo, pero explica que su mayor logro es ver a nuevas generaciones confiar en sus capacidades.',gloss:[['comenzó','a commencé'],['dirigió','a dirigé'],['logro','réussite']],q:'¿Qué considera Elena su mayor logro?',options:['Recibir premios','Dirigir un laboratorio','Inspirar a otras jóvenes'],answer:2,pron:'Creó talleres para que las jóvenes descubrieran nuevas profesiones.'},
  perfil:{title:'Una oferta para el verano',text:'Una empresa de turismo busca a una persona para atender a visitantes durante el verano. Es preciso que el candidato sea amable, puntual y capaz de trabajar en equipo. También debe hablar español y manejar herramientas digitales sencillas. No se exige experiencia larga, pero se valora haber participado en proyectos escolares o asociativos.',gloss:[['busca','recherche'],['se exige','on exige'],['se valora','on apprécie']],q:'¿Qué experiencia puede resultar útil?',options:['Solo un empleo de cinco años','Un proyecto escolar o asociativo','Ninguna actividad'],answer:1,pron:'Soy una persona puntual, organizada y capaz de trabajar en equipo.'},
  erasmus:{title:'La decisión de Samir',text:'Samir realizará una movilidad de cuatro semanas en Valencia. Trabajará en una empresa relacionada con su especialidad y vivirá con otros estudiantes europeos. Quiere mejorar su español, descubrir otra forma de trabajar y ganar autonomía. Sabe que tendrá que adaptarse a nuevos horarios, pero considera que esta experiencia le abrirá puertas profesionales.',gloss:[['realizará','il effectuera'],['ganar autonomía','gagner en autonomie'],['le abrirá puertas','lui ouvrira des portes']],q:'¿Qué dificultad anticipa Samir?',options:['Adaptarse a nuevos horarios','Encontrar su especialidad','Aprender francés'],answer:0,pron:'Esta movilidad me permitirá mejorar mi español y ganar autonomía.'},
  planeta:{title:'Un instituto reduce sus residuos',text:'El consejo de alumnos ha observado que la cafetería produce demasiados residuos. Por eso propone instalar fuentes de agua, utilizar recipientes reutilizables y organizar mejor la separación de basura. Algunos cambios costarán dinero, pero el grupo piensa que reducirán los gastos a largo plazo. También quiere informar a las familias para que participen.',gloss:[['fuentes de agua','fontaines à eau'],['recipientes','récipients'],['a largo plazo','à long terme']],q:'¿Por qué informarán a las familias?',options:['Para que también participen','Para vender recipientes','Para cerrar la cafetería'],answer:0,pron:'Podríamos reducir los residuos utilizando recipientes reutilizables.'},
  colombia:{title:'Un país de muchas voces',text:'Colombia reúne regiones, paisajes y comunidades muy diferentes. En las últimas décadas, sus ciudades han desarrollado proyectos culturales, científicos y tecnológicos reconocidos internacionalmente. Sin embargo, algunos medios extranjeros siguen mostrando una imagen limitada del país. Jóvenes creadores utilizan vídeos, música y fotografía para presentar realidades más diversas y combatir los prejuicios.',gloss:[['reúne','rassemble'],['han desarrollado','ont développé'],['siguen mostrando','continuent à montrer']],q:'¿Qué hacen los jóvenes creadores?',options:['Repiten una imagen limitada','Presentan realidades diversas','Evitan hablar del país'],answer:1,pron:'Colombia no solo tiene paisajes, sino también una gran diversidad cultural.'},
  arte:{title:'Un muro que hace preguntas',text:'En una plaza aparece un mural con rostros de diferentes edades. Las figuras están mirando hacia una puerta cerrada y una niña sostiene una llave. La artista no explica un único significado: invita al público a reflexionar sobre quién puede participar en la sociedad. Algunas personas ven esperanza; otras interpretan la puerta como un símbolo de desigualdad.',gloss:[['rostros','visages'],['sostiene','tient'],['una llave','une clé']],q:'¿Por qué la artista no explica un solo significado?',options:['Porque olvidó su obra','Para invitar a la reflexión','Porque nadie puede verla'],answer:1,pron:'La puerta puede simbolizar un obstáculo o una oportunidad.'},
  bac:{title:'Comprender con método',text:'Durante una prueba de comprensión no es necesario traducir cada palabra. Primero identifica la naturaleza del documento, las personas, el lugar y el tema principal. Después busca las informaciones importantes y los conectores. Al final, organiza tus notas y explica el objetivo del documento. Si una palabra es desconocida, utiliza el contexto antes de preocuparte.',gloss:[['la prueba','l’épreuve'],['las notas','les notes'],['desconocida','inconnue']],q:'¿Qué debes identificar primero?',options:['Todas las palabras','La naturaleza y el tema','La traducción exacta'],answer:1,pron:'Primero identifico el documento; después organizo las informaciones.'}
};
const gap=(sentence,fr,answer,hint)=>({sentence,fr,answer,hint});
window.UNIT_CLOZE={
  bienvenido:[gap('Me ___ Lucía y tengo quince años.','Je m’appelle Lucía et j’ai quinze ans.','llamo','LLAMARSE'),gap('Mis clases ___ a las ocho.','Mes cours commencent à huit heures.','empiezan','EMPEZAR')],
  deporte:[gap('Yo me ___ los miércoles.','Je m’entraîne le mercredi.','entreno','ENTRENARSE'),gap('No ___ jugar hoy porque estoy cansado.','Je ne peux pas jouer aujourd’hui.','puedo','PODER')],
  malaga:[gap('En el centro ___ una catedral.','Dans le centre, il y a une cathédrale.','hay','HAY / ESTÁ'),gap('Tienes que ___ a la derecha.','Tu dois tourner à droite.','girar','TENER QUE + infinitif')],
  comida:[gap('Me ___ las tapas vegetarianas.','J’aime les tapas végétariennes.','gustan','GUSTAR'),gap('Primero se ___ los tomates.','On coupe d’abord les tomates.','cortan','SE + verbo')],
  moda:[gap('La camisa blanca es ___ elegante que la sudadera.','La chemise blanche est plus élégante que le sweat.','más','COMPARATIVO'),gap('Lleva unos zapatos ___.','Elle porte des chaussures confortables.','cómodos','ACUERDO')],
  series:[gap('Los personajes están ___ un misterio.','Les personnages enquêtent sur un mystère.','investigando','ESTAR + gerundio'),gap('Te recomiendo que ___ esta serie.','Je te recommande de regarder cette série.','veas','SUBJUNTIVO')],
  'pura-vida':[gap('Mañana ___ un parque natural.','Demain, nous visiterons un parc naturel.','visitaremos','FUTURO'),gap('¿___ cuesta la habitación?','Combien coûte la chambre ?','cuánto','INTERROGATIVO')],
  fiesta:[gap('Es la fiesta ___ conocida de la región.','C’est la fête la plus connue de la région.','más','SUPERLATIVO'),gap('Hay ___ gente que las calles están llenas.','Il y a tellement de monde que les rues sont pleines.','tanta','TAN / TANTO')],
  tecnologias:[gap('Te aconsejo que ___ una contraseña segura.','Je te conseille de choisir un mot de passe sûr.','elijas','SUBJUNTIVO'),gap('Antes mis abuelos no ___ videollamadas.','Avant, mes grands-parents ne faisaient pas d’appels vidéo.','hacían','IMPERFECTO')],
  mujeres:[gap('En 2015 ella ___ una asociación.','En 2015, elle a fondé une association.','fundó','INDEFINIDO'),gap('Luchó ___ defender sus derechos.','Elle a lutté pour défendre ses droits.','para','FINALIDAD')],
  perfil:[gap('Es preciso que el candidato ___ organizado.','Le candidat doit être organisé.','sea','SUBJUNTIVO'),gap('El año pasado ___ prácticas en una tienda.','L’année dernière, j’ai fait un stage en magasin.','hice','HACER · INDEFINIDO')],
  erasmus:[gap('Durante mi movilidad ___ en Valencia.','Pendant ma mobilité, je travaillerai à Valence.','trabajaré','FUTURO'),gap('Me ___ descubrir otra cultura profesional.','J’aimerais découvrir une autre culture professionnelle.','gustaría','CONDICIONAL')],
  planeta:[gap('Me preocupa que desaparezcan muchas ___.','La disparition de nombreuses espèces m’inquiète.','especies','LÉXICO'),gap('Nosotros ___ reducir los residuos.','Nous pourrions réduire les déchets.','podríamos','CONDICIONAL')],
  colombia:[gap('Colombia ha ___ mucho en los últimos años.','La Colombie a beaucoup changé ces dernières années.','cambiado','PRETÉRITO PERFECTO'),gap('Creamos esta campaña para que el público ___.','Nous créons cette campagne pour que le public réfléchisse.','reflexione','FINALIDAD + subjuntivo')],
  arte:[gap('La artista protesta ___ un mural.','L’artiste proteste en peignant une fresque.','pintando','GERUNDIO'),gap('No ___ ante la injusticia.','Ne te tais pas face à l’injustice.','calles','IMPERATIVO NEGATIVO')],
  bac:[gap('___, identifico la naturaleza del documento.','D’abord, j’identifie la nature du document.','primero','CONECTOR'),gap('Para ___, doy mi opinión personal.','Pour conclure, je donne mon avis personnel.','concluir','CONCLUSIÓN')]
};
